Artsem / My Profile page fix styles
carol-binary/deriv-app pull request #30
Opened 2022-02-22 11:35 UTC by artsemkavaleu-deriv

2022-02-24 07:39 UTC, carol-binary requested changes

2022-02-24 07:39 UTC, carol-binary commented on packages/p2p/src/components/misc/toggle-container.scss
> +        margin-bottom: 4.8rem;
Let's give this as `margin: 2.4rem 0 4.8rem;`

2022-02-24 07:39 UTC, carol-binary commented on packages/p2p/src/components/my-profile/my-profile-stats/my-profile-stats-table/my-profile-stats-table.jsx
> +                                />
Let's wrap this to show only if `total_turnover` exists because right now if it doesn't, it'll show `- USD` for example, which wouldn't be right.

2022-02-24 07:39 UTC, carol-binary commented on packages/p2p/src/components/my-profile/my-profile-stats/my-profile-stats-table/my-profile-stats-table.jsx
> +                            />
Same here.

2022-02-24 08:48 UTC, artsemkavaleu-deriv commented on packages/p2p/src/components/my-profile/my-profile-stats/my-profile-stats-table/my-profile-stats-table.jsx
> +                                />
done, thx for notice!

2022-02-24 08:48 UTC, artsemkavaleu-deriv commented on packages/p2p/src/components/my-profile/my-profile-stats/my-profile-stats-table/my-profile-stats-table.jsx
> +                            />
done, thx for notice!

2022-02-24 08:48 UTC, artsemkavaleu-deriv commented on packages/p2p/src/components/misc/toggle-container.scss
> +        margin-bottom: 4.8rem;
sure, done

2022-02-25 08:42 UTC, carol-binary approved these changes

2022-02-25 08:51 UTC, merged